function Invoke-CleanAppList {
    Param(
        [Parameter(Mandatory = $true)]
        [string]$RawAppList # path the the raw app list generated by the Packages Names app
    )

    Write-Host "Cleaning app list..."

    # import the raw app list
    $lines = Import-Csv -Path $RawAppList -Delimiter ","
    
    # select only the package names
    $cleanedLines = $lines | Select-Object -ExpandProperty "PackageName"

    # remove empty lines
    $cleanedLines = $cleanedLines | Where-Object { $_ }

    Write-Host "App list cleaned successfully."

    return $cleanedLines
}
$projectRoot = Split-Path $PSScriptRoot -Parent # path to the project root

$a = Invoke-CleanAppList $projectRoot/test-ressources/apps.csv

Write-Host $a