function Invoke-CleanAppList {
    Param(
        [Parameter(Mandatory = $true)]
        [string]$RawAppList # path the the raw app list generated by the Packages Names app
    )

    Write-Host "Cleaning app list..."

    $lines = Get-Content -Path $RawAppList # all lines in the file
    $cleanedLines = @() # array to store the cleaned lines
    
    # keep the 2nd line of every block of 3 lines
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if (($i % 3) -eq 1) {
            $cleanedLines += $lines[$i].Trim()
        }
    }

    Write-Host "App list cleaned successfully."

    return $cleanedLines
}